events {
    worker_connections 1024;
}

http {
    upstream svc-rooms-upstream {
        server svc-rooms:8081;
    }

    upstream svc-reservations-upstream {
        server svc-reservations:8082;
    }

    server {
        listen 80;

        # Gateway routing: /api/v1/rooms/* -> svc-rooms
        location /api/v1/rooms {
            proxy_pass http://svc-rooms-upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Gateway routing: /api/v1/reservations/* -> svc-reservations
        location /api/v1/reservations {
            proxy_pass http://svc-reservations-upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
